switch to debian image for hugo build
This is how the statius site is built, and I cannot reproduce the hugo
build locally with the provided image here, podman refuses to pull the
image:

anarcat@angela:dev$ podman run registry.gitlab.com/pages/hugo/hugo_extended
Trying to pull registry.gitlab.com/pages/hugo/hugo_extended:latest...
Error: initializing source docker://registry.gitlab.com/pages/hugo/hugo_extended:latest: unable to retrieve auth token: invalid username/password: unauthorized: HTTP Basic: Access denied. The provided password or token is incorrect or your account has 2FA enabled and you must use a personal access token instead of a password. See https://gitlab.com/help/user/profile/account/two_factor_authentication#troubleshooting
anarcat@angela:dev[125]$ d